- name: Delete file in Dynatrace server
  hosts: all
  become: yes

  tasks:
          
          - name: Get the current timestamp
            set_fact:
              timestamp: "{{ lookup('pipe', 'date +%Y-%m-%d_%H:%M:%S') }}"

          - name: Append Message to file
            lineinfile:
              path: /home/azureuser/log.txt
              line: "{{ timestamp }} - Ansible tower connected"
              insertafter: EOF
              
          - name: Remove file from path /home/azureuser
            file:
                    path: /home/azureuser/q1.log
                    state: absent

          - name: Create a log file
            file:
                    path: /home/azureuser/q1.log
                    state: touch