- name: Restart the HTTP server in application host
  hosts: all
  become: yes

  tasks:
          - name: Get the current timestamp
            set_fact:
              timestamp: "{{ lookup('pipe', 'date +%Y-%m-%d_%H:%M:%S') }}"

          - name: Append Message to file
            lineinfile:
              path: /home/azureuser/log.txt
              line: "{{ timestamp }} - Ansible tower connected"
              insertafter: EOF

          - name: Check if HTTP server is up
            uri:
              url: http://172.172.243.139/
              method: GET
            register: result
            ignore_errors: yes
          
          - name: Print Result
            debug:
              msg: "HTTP server is {{'up' if result.status == 200 else 'down'}}"

          - name: Restart HTTP server if it is down
            command: sudo systemctl restart apache2
            when: result.status != 200